### ISSUE TITLE
'categories' information empty in ParquetFile repr

### ISSUE THREAD

**Issue by d10genes** [dask/fastparquet#67] opened 2017-01-06 14:00 UTC
If I write a df with a categorical column

```
> d = DataFrame({'A': [1, 2, 3], 'B': ['a', 'b', 'c']}).assign(B=lambda x: x.B.astype('category'))
> d.dtypes
A       int64
B    category
dtype: object
> fn = '/tmp/test.parq'
> fastparquet.write(fn, d)
```

then create a ParquetFile, the 'categories' entry in the repr shows nothing. Does categories here refer to something else?

```
> pf = fastparquet.ParquetFile(fn)
> pf
<Parquet File: {'categories': [], 'rows': 3, 'columns': ['A', 'B'], 'name': '/tmp/test.parq'}>
```

(I noticed one needs to manually designate categorical columns when converting to df, so I'd like to find a way to store this as metadata and convert to categorical automatically without too much manual bookkeeping)

**Comment by martindurant** [comment] 2017-01-06 14:43
The "categories" refer to labels derived from the folder partitioning structure, not from dictionary-encoded column data. I realise the word is used in multiple contexts... For the partitioning, the resultant columns are guaranteed to be "category" dtype. 
As for the second question, the parquet format has no concept of a column which is dictionary encoded in every column chunk - there could easily be some that are and some that aren't. Files written by fastparquet will be consistent by design, however, so it is conceivable to special-case self-written files. I'm not immediately sure how - storing the categories themselves in metadata seems like needless repetition (and we don't want to explode the size of the metadata).

**Comment by d10genes** [comment] 2017-01-06 19:37
Thanks so much for the quick reply.

I'm not quite making sense of what you call `special-case self-written files.`

Does this just mean finding a custom way to embed which columns are categorical in the dataframe before writing it?

**Comment by martindurant** [comment] 2017-01-06 21:37
I mean, when fastparquet writes a file, it identifies itself as the file creator in the metadata. Thus, we could create an internal standard for indicating that a column is categorical, for reading files written by fastparquet. When reading a file made by any other parquet writer, however, we would be in the same situation of not knowing whether all the chunks are dictionary encoded.

**Comment by martindurant** [comment] 2017-01-11 22:02
Closing as "expected behaviour", but you are welcome to suggest better wording/documentation.

**Closed by martindurant** 2017-01-11 22:02 UTC

**Comment by d10genes** [comment] 2017-01-13 14:38
Would this internal standard need to be built in to the library, or does fastparquet expose some hook for the user to write some custom metadata?

**Comment by martindurant** [comment] 2017-01-13 14:48
No, there is no such hook, the user cannot write directly to the metadata. It's not such a bad idea, though, I see where you are going with that.
