### ISSUE TITLE
cython speedups failing

### ISSUE THREAD

**Issue by yalwan-scee** [dask/fastparquet#94] opened 2017-02-28 16:58 UTC
When I was testing 0.5 release with a script I had used previous without issue, I came across the following issue:

```    fastparquet.write(fname, df, file_scheme='hive', has_nulls=True, object_encoding='utf8', compression='SNAPPY')
  File "/home/yalwan/.virtualenvs/fastpq/lib/python3.5/site-packages/fastparquet/writer.py", line 781, in write
    compression=compression)
  File "/home/yalwan/.virtualenvs/fastpq/lib/python3.5/site-packages/fastparquet/writer.py", line 580, in make_part_file
    rg = make_row_group(f, data, schema, compression=compression)
  File "/home/yalwan/.virtualenvs/fastpq/lib/python3.5/site-packages/fastparquet/writer.py", line 568, in make_row_group
    compression=comp)
  File "/home/yalwan/.virtualenvs/fastpq/lib/python3.5/site-packages/fastparquet/writer.py", line 484, in write_column
    data, selement)
  File "/home/yalwan/.virtualenvs/fastpq/lib/python3.5/site-packages/fastparquet/writer.py", line 246, in encode_plain
    out = convert(data, se)
  File "/home/yalwan/.virtualenvs/fastpq/lib/python3.5/site-packages/fastparquet/writer.py", line 154, in convert
    out = array_encode_utf8(data)
  File "fastparquet/speedups.pyx", line 58, in fastparquet.speedups.array_encode_utf8 (fastparquet/speedups.c:2296)
TypeError: bad argument type for built-in operation
```

**Comment by martindurant** [comment] 2017-02-28 17:16
Can you find out what the data causing the problem is? What are your input data types, and what set of options are you passing to `write()`? Also, this may depend on the version of python you are using.
Ideally, we'd like to see a self-contained example, so we can include it in tests.

**Comment by yalwan-scee** [comment] 2017-03-01 10:34
I found out that this is a dense error relating to no support for date types. Does this project intend to support date types (as opposed to datetime)?

**Comment by martindurant** [comment] 2017-03-01 13:43
I assume you mean python dates objects, in an object-type column. This is not supported. Pandas datetimes are normally what you want, e.g., by calling `pd.to_datetime` on your column.

**Comment by mrocklin** [comment] 2017-03-01 14:00
Does parquet have a separate date type?

**Comment by martindurant** [comment] 2017-03-01 14:06
Yes, parquet has a [date type](https://github.com/Parquet/parquet-format/blob/master/LogicalTypes.md#date). On load, these become datetime64 objects just like timestamps, even though it is stored as int32.

**Comment by martindurant** [comment] 2017-03-01 14:29
Do you think it's worth adding another option to `object_encoding` to deal with dates? The first step of the conversion would be to timestamp64 with to_datetime, but this would be the only way of saving lower-precision int32 timestamps; they would load to timestamp64 just the same, though.

**Comment by mrocklin** [comment] 2017-03-01 14:31
I don't think this is worth thinking about at the object level.  I agree
that we shouldn't handle Python date objects except possibly by raising and
telling the user to convert them to numpy/pandas.

I think that explicit support for date objects might make sense if given
Numpy arrays or Pandas series with dtype `M8[d]`.  This probably isn't that
important for as long as fastparquet mostly just cares about Pandas and not
about NumPy.

**Comment by martindurant** [comment] 2017-03-01 16:40
Closing for now. Creating DATE type columns will not be considered in the immediate future.

**Closed by martindurant** 2017-03-01 16:40 UTC

**Comment by yalwan-scee** [comment] 2017-03-03 09:15
Can you consider date support? The Python date objects are what come out of pyODBC so I'm not convinced it is unreasonable.

This is the code I use:

```
conn            = pyodbc.connect()
df_array       = pandas.read_sql_query('select * from %s' % table, conn, chunksize=n)
```

**Comment by martindurant** [comment] 2017-03-03 16:00
(this should really be a separate issue or a StackOverflow question)

It could be done, but I am wary of accepting too many object types. 
Note that [read_sql_query](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql_query.html) has a `parse_dates` parameter that I think will convert automatically for you.

**Comment by yalwan-scee** [comment] 2017-03-03 16:46
Sorry for dragging this on.

I'll try your suggestion, although I'm a bit concerned about the performance of that function. If it is adequate, I'll stick with it, and if not, I'll raise a new issue.

Thanks for your help.
