### ISSUE TITLE
output performance Windows 10, local SSD file system

### ISSUE THREAD

**Issue by apiszcz** [dask/fastparquet#235] opened 2017-10-09 10:03 UTC
Observation of speed difference with arrow and fastparquet.write

```
arrow
papq.write_table(pa.Table.from_pandas(df),opath)
data1,62,462 records 866,927 rec/sec,
data2,62,489 records 918,301 rec/sec,
data3,62,343 records 915,963 rec/sec,
data4,62,691 records 935,022 rec/sec,
data5,62,257 records 888,799 rec/sec,
```

```
fastparquet has a possible jit cost for first write? then improves.
fastparquet.write(opath,df)
 data1,62,462 records,   226,986 rec/sec, 
 data2,62,489 records, 1,601,135 rec/sec,
 data3,62,343 records, 1,519,548 rec/sec,
 data4,62,691 records, 1,566,249 rec/sec,
 data5,62,257 records, 1,556,055 rec/sec,
```

**Comment by mrocklin** [comment] 2017-10-09 12:15
I suspect that @wesm will be interested in these numbers.  He'll probably also be interested in what kind of data you were writing.  Do you happen to have an example that others can reproduce easily?

**Comment by apiszcz** [comment] 2017-10-09 12:44
15 fields, 8 floats, 1 string, 7 integers
I generate these with random data for most fields.
I'm noticing some things breaking with dask 0.15.4/fastparquet is the
'final'? https://github.com/dask/fastparquet/issues/234

f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15
0.0,1970-01-01T00:00:00.000000,1.1296639979509104,1.0162722063447531,34,51,0.9946934069700644,0.542349895094777,0.49885798300550743,0.13526604392792918,35,2,7,49,68
0.0864000864000864,1970-01-01T00:00:00.086400,0.481989272786288,0.6692591452690444,54,63,0.11588928583687774,0.9225951457173023,0.4394392828560898,0.48286035348785716,0,32,0,76,14

**Comment by wesm** [comment] 2017-10-09 13:07
> I generate these with random data for most fields. 

Can you supply code for making your benchmarks reproducible?

**Comment by apiszcz** [comment] 2017-10-09 13:11
Questions/Answers? maybe: I posted the lines I'm using to write the file. here are the imports. Perhaps I'm doing something wrong, I can probably create a small test to demonstrate this.

```
import pyarrow as pa
import pyarrow.parquet as papq

papq.write_table(pa.Table.from_pandas(gclean),opqpath)
fastparquet.write(opqpath,gclean)
```

**Comment by wesm** [comment] 2017-10-09 13:16
You aren't doing anything wrong, but reproducible benchmarks require both data (or code to generate the data) and the code for the benchmarks. 

From the docstring for http://fastparquet.readthedocs.io/en/latest/api.html#fastparquet.write I am inferring that fastparquet does not do dictionary encoding. So to make this an apples-to-apples comparison you should pass `use_dictionary=False` to `pyarrow.parquet.write_Table`. Please also use the same compression codec -- pyarrow uses Snappy by default, it looks like the default for fastparquet is uncompressed

**Comment by apiszcz** [comment] 2017-10-09 13:21
First take, need to add your recommendations next.

![image](https://user-images.githubusercontent.com/1430861/31340127-34b2302a-acd3-11e7-8966-376ac5008597.png)

**Comment by apiszcz** [comment] 2017-10-09 13:27
![image](https://user-images.githubusercontent.com/1430861/31340431-14fad768-acd4-11e7-9326-674405ccd6e0.png)

**Comment by apiszcz** [comment] 2017-10-09 13:30
With SNAPPY set. Increased to 10,000 rows.
![image](https://user-images.githubusercontent.com/1430861/31340533-71e2263e-acd4-11e7-8715-0bd93f1dc555.png)

**Comment by apiszcz** [comment] 2017-10-09 13:32
1 and 10 million rows

![image](https://user-images.githubusercontent.com/1430861/31340569-930494d2-acd4-11e7-98b0-615856348c33.png)

![image](https://user-images.githubusercontent.com/1430861/31340641-d5c426ac-acd4-11e7-86ea-7bbde58b378c.png)

**Comment by apiszcz** [comment] 2017-10-09 13:36
10 million rows with floats

![image](https://user-images.githubusercontent.com/1430861/31340795-4e57c632-acd5-11e7-894d-b74ed9008c04.png)

**Comment by martindurant** [comment] 2017-10-09 13:38
I am happy for fastparquet to be 13% slower than arrow, if that's the case.
You might find it interesting to also compare with smaller dtypes like int8 and float32. You'll probably do text next, so you should know that fastparquet is much faster for bytes-type, and has a fixed= parameter for some optimisation too.

**Comment by martindurant** [comment] 2017-10-09 13:39
Note that many people will ask you to post text rather than images, because they are searchable and copy-pastable.

**Comment by apiszcz** [comment] 2017-10-09 13:42
import pyarrow as pa
import pyarrow.parquet as papq
import numpy as np
import pandas as pd
import fastparquet

df=pd.DataFrame(np.random.rand(10000000,15),columns=list('0123456789abcde'))
%timeit papq.write_table(pa.Table.from_pandas(df),'test.papq',use_dictionary=False,compression='snappy')
%timeit fastparquet.write('test.fastpq',df,compression='SNAPPY')

6.08 s ± 77.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
10 s ± 374 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by apiszcz** [comment] 2017-10-09 13:46
```python
import pyarrow as pa
import pyarrow.parquet as papq
import numpy as np
import pandas as pd
import fastparquet
```


```python
#df=pd.DataFrame(np.random.randint(0,100,(10000000,15)),columns=list('0123456789abcde'))
df=pd.DataFrame(np.random.rand(10000000,15),columns=list('0123456789abcde'))
%timeit papq.write_table(pa.Table.from_pandas(df),'test.papq',use_dictionary=False,compression='snappy')
%timeit fastparquet.write('test.fastpq',df,compression='SNAPPY')
```

    6.08 s ± 77.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
    10 s ± 374 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by martindurant** [comment] 2017-10-09 13:59
Interestingly, significant time it spent in fastparquet on finding if there are any nulls in the data (there aren't) and calculating the max/min of the column for the statistics metadata (which is not very informative in this case). The rest of the inefficiency in in copying blocks of bytes.

**Comment by apiszcz** [comment] 2017-10-09 14:01
Retest in my situation with use_dictionary=False and compression='snappy

```
parquet,       62,448 records, actual    1,155,538 rec/sec
parquet,       62,824 records, actual    1,184,682 rec/sec
parquet,       62,378 records, actual    1,154,319 rec/sec
parquet,       62,417 records, actual    1,223,013 rec/sec
parquet,       62,970 records, actual    1,123,684 rec/sec

use_dictionary=False
arrow,       62,620 records, actual    1,379,066 rec/sec,
arrow,       62,185 records, actual    1,635,334 rec/sec,
arrow,       62,613 records, actual    1,604,342 rec/sec,
arrow,       62,286 records, actual    1,595,242 rec/sec,
arrow,       62,280 records, actual    1,637,155 rec/sec,
2,007 files, 441MB

use_dictionary=True
arrow,       62,620 records, actual      903,965 rec/sec,
arrow,       62,185 records, actual      839,749 rec/sec
arrow,       62,613 records, actual      920,097 rec/sec
arrow,       62,286 records, actual      928,978 rec/sec
arrow,       62,280 records, actual      915,393 rec/sec
2,007 files, 441MB
```

**Closed** 2018-11-26 14:30 UTC
